import { Config } from "effect"
import { InstallationChannel } from "../installation/version"

function truthy(key: string) {
  const value = process.env[key]?.toLowerCase()
  return value === "true" || value === "1"
}

function falsy(key: string) {
  const value = process.env[key]?.toLowerCase()
  return value === "false" || value === "0"
}

const UNSTABLE_CHANNELS = new Set(["dev", "beta", "local"])
function unstableDefault(key: string) {
  return truthy(key) || (!falsy(key) && UNSTABLE_CHANNELS.has(InstallationChannel))
}

function number(key: string) {
  const value = process.env[key]
  if (!value) return undefined
  const parsed = Number(value)
  return Number.isInteger(parsed) && parsed > 0 ? parsed : undefined
}

const ACCURECODE_EXPERIMENTAL = truthy("ACCURECODE_EXPERIMENTAL")
const ACCURECODE_DISABLE_CLAUDE_CODE = truthy("ACCURECODE_DISABLE_CLAUDE_CODE")
const ACCURECODE_DISABLE_CLAUDE_CODE_SKILLS =
  ACCURECODE_DISABLE_CLAUDE_CODE || truthy("ACCURECODE_DISABLE_CLAUDE_CODE_SKILLS")
const copy = process.env["ACCURECODE_EXPERIMENTAL_DISABLE_COPY_ON_SELECT"]

export const Flag = {
  OTEL_EXPORTER_OTLP_ENDPOINT: process.env["OTEL_EXPORTER_OTLP_ENDPOINT"],
  OTEL_EXPORTER_OTLP_HEADERS: process.env["OTEL_EXPORTER_OTLP_HEADERS"],

  ACCURECODE_AUTO_SHARE: truthy("ACCURECODE_AUTO_SHARE"),
  ACCURECODE_AUTO_HEAP_SNAPSHOT: truthy("ACCURECODE_AUTO_HEAP_SNAPSHOT"),
  ACCURECODE_GIT_BASH_PATH: process.env["ACCURECODE_GIT_BASH_PATH"],
  ACCURECODE_CONFIG: process.env["ACCURECODE_CONFIG"],
  ACCURECODE_CONFIG_CONTENT: process.env["ACCURECODE_CONFIG_CONTENT"],
  ACCURECODE_DISABLE_AUTOUPDATE: truthy("ACCURECODE_DISABLE_AUTOUPDATE"),
  ACCURECODE_ALWAYS_NOTIFY_UPDATE: truthy("ACCURECODE_ALWAYS_NOTIFY_UPDATE"),
  ACCURECODE_DISABLE_PRUNE: truthy("ACCURECODE_DISABLE_PRUNE"),
  ACCURECODE_DISABLE_TERMINAL_TITLE: truthy("ACCURECODE_DISABLE_TERMINAL_TITLE"),
  ACCURECODE_SHOW_TTFD: truthy("ACCURECODE_SHOW_TTFD"),
  ACCURECODE_DISABLE_DEFAULT_PLUGINS: truthy("ACCURECODE_DISABLE_DEFAULT_PLUGINS"),
  ACCURECODE_DISABLE_LSP_DOWNLOAD: truthy("ACCURECODE_DISABLE_LSP_DOWNLOAD"),
  ACCURECODE_ENABLE_EXPERIMENTAL_MODELS: truthy("ACCURECODE_ENABLE_EXPERIMENTAL_MODELS"),
  ACCURECODE_DISABLE_AUTOCOMPACT: truthy("ACCURECODE_DISABLE_AUTOCOMPACT"),
  ACCURECODE_DISABLE_MODELS_FETCH: truthy("ACCURECODE_DISABLE_MODELS_FETCH"),
  ACCURECODE_DISABLE_MOUSE: truthy("ACCURECODE_DISABLE_MOUSE"),
  ACCURECODE_DISABLE_CLAUDE_CODE,
  ACCURECODE_DISABLE_CLAUDE_CODE_PROMPT:
    ACCURECODE_DISABLE_CLAUDE_CODE || truthy("ACCURECODE_DISABLE_CLAUDE_CODE_PROMPT"),
  ACCURECODE_DISABLE_CLAUDE_CODE_SKILLS,
  ACCURECODE_DISABLE_EXTERNAL_SKILLS: truthy("ACCURECODE_DISABLE_EXTERNAL_SKILLS"),
  ACCURECODE_EXPERIMENTAL_CUSTOMIZE_SKILL: unstableDefault("ACCURECODE_EXPERIMENTAL_CUSTOMIZE_SKILL"), // accurecode_change
  ACCURECODE_FAKE_VCS: process.env["ACCURECODE_FAKE_VCS"],
  ACCURECODE_SERVER_PASSWORD: process.env["ACCURECODE_SERVER_PASSWORD"],
  ACCURECODE_SERVER_USERNAME: process.env["ACCURECODE_SERVER_USERNAME"],
  ACCURECODE_ENABLE_QUESTION_TOOL: truthy("ACCURECODE_ENABLE_QUESTION_TOOL"),

  ACCURECODE_EXPERIMENTAL,
  ACCURECODE_EXPERIMENTAL_FILEWATCHER: Config.boolean("ACCURECODE_EXPERIMENTAL_FILEWATCHER").pipe(
    Config.withDefault(false),
  ),
  ACCURECODE_EXPERIMENTAL_DISABLE_FILEWATCHER: Config.boolean("ACCURECODE_EXPERIMENTAL_DISABLE_FILEWATCHER").pipe(
    Config.withDefault(false),
  ),
  ACCURECODE_EXPERIMENTAL_ICON_DISCOVERY: ACCURECODE_EXPERIMENTAL || truthy("ACCURECODE_EXPERIMENTAL_ICON_DISCOVERY"),
  ACCURECODE_EXPERIMENTAL_DISABLE_COPY_ON_SELECT:
    copy === undefined ? process.platform === "win32" : truthy("ACCURECODE_EXPERIMENTAL_DISABLE_COPY_ON_SELECT"),
  ACCURECODE_ENABLE_EXA:
    truthy("ACCURECODE_ENABLE_EXA") || ACCURECODE_EXPERIMENTAL || truthy("ACCURECODE_EXPERIMENTAL_EXA"),
  ACCURECODE_EXPERIMENTAL_BASH_DEFAULT_TIMEOUT_MS: number("ACCURECODE_EXPERIMENTAL_BASH_DEFAULT_TIMEOUT_MS"),
  ACCURECODE_EXPERIMENTAL_OUTPUT_TOKEN_MAX: number("ACCURECODE_EXPERIMENTAL_OUTPUT_TOKEN_MAX"),
  ACCURECODE_EXPERIMENTAL_OXFMT: ACCURECODE_EXPERIMENTAL || truthy("ACCURECODE_EXPERIMENTAL_OXFMT"),
  ACCURECODE_EXPERIMENTAL_LSP_TY: truthy("ACCURECODE_EXPERIMENTAL_LSP_TY"),
  ACCURECODE_EXPERIMENTAL_LSP_TOOL: ACCURECODE_EXPERIMENTAL || truthy("ACCURECODE_EXPERIMENTAL_LSP_TOOL"),
  ACCURECODE_EXPERIMENTAL_PLAN_MODE: ACCURECODE_EXPERIMENTAL || truthy("ACCURECODE_EXPERIMENTAL_PLAN_MODE"),
  ACCURECODE_EXPERIMENTAL_SCOUT: ACCURECODE_EXPERIMENTAL || truthy("ACCURECODE_EXPERIMENTAL_SCOUT"),
  ACCURECODE_EXPERIMENTAL_MARKDOWN: !falsy("ACCURECODE_EXPERIMENTAL_MARKDOWN"),
  ACCURECODE_ENABLE_PARALLEL: truthy("ACCURECODE_ENABLE_PARALLEL") || truthy("ACCURECODE_EXPERIMENTAL_PARALLEL"),
  ACCURECODE_MODELS_URL: process.env["ACCURECODE_MODELS_URL"],
  ACCURECODE_MODELS_PATH: process.env["ACCURECODE_MODELS_PATH"],
  ACCURECODE_DISABLE_EMBEDDED_WEB_UI: truthy("ACCURECODE_DISABLE_EMBEDDED_WEB_UI"),
  ACCURECODE_DB: process.env["ACCURECODE_DB"],
  ACCURECODE_DISABLE_CHANNEL_DB: truthy("ACCURECODE_DISABLE_CHANNEL_DB"),
  ACCURECODE_SKIP_MIGRATIONS: truthy("ACCURECODE_SKIP_MIGRATIONS"),
  ACCURECODE_STRICT_CONFIG_DEPS: truthy("ACCURECODE_STRICT_CONFIG_DEPS"),

  ACCURECODE_WORKSPACE_ID: process.env["ACCURECODE_WORKSPACE_ID"],
  ACCURECODE_EXPERIMENTAL_WORKSPACES: ACCURECODE_EXPERIMENTAL || truthy("ACCURECODE_EXPERIMENTAL_WORKSPACES"),
  ACCURECODE_EXPERIMENTAL_EVENT_SYSTEM: ACCURECODE_EXPERIMENTAL || truthy("ACCURECODE_EXPERIMENTAL_EVENT_SYSTEM"),
  ACCURECODE_EXPERIMENTAL_SESSION_SWITCHING:
    ACCURECODE_EXPERIMENTAL || truthy("ACCURECODE_EXPERIMENTAL_SESSION_SWITCHING"),

  get ACCURECODE_DISABLE_PROJECT_CONFIG() {
    return truthy("ACCURECODE_DISABLE_PROJECT_CONFIG")
  },
  get ACCURECODE_TUI_CONFIG() {
    return process.env["ACCURECODE_TUI_CONFIG"]
  },
  get ACCURECODE_CONFIG_DIR() {
    return process.env["ACCURECODE_CONFIG_DIR"]
  },
  get ACCURECODE_PURE() {
    return truthy("ACCURECODE_PURE")
  },
  get ACCURECODE_PERMISSION() {
    return process.env["ACCURECODE_PERMISSION"]
  },
  get ACCURECODE_PLUGIN_META_FILE() {
    return process.env["ACCURECODE_PLUGIN_META_FILE"]
  },
  get ACCURECODE_CLIENT() {
    return process.env["ACCURECODE_CLIENT"] ?? "cli"
  },
  get ACCURECODE_SESSION_RETRY_LIMIT() {
    return number("ACCURECODE_SESSION_RETRY_LIMIT")
  },
}
